name = "LiterateOrg"
uuid = "93c33440-6125-11e8-0ffd-df540d4e821e"
authors = ["Stefanos Carlstr√∂m <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
